Add 300 sentences
kjanko/deep-speech-mk-sentences pull request #3
Opened 2017-10-27 08:44 UTC by macko996

2017-10-27 17:44 UTC, kjanko commented on macko996-2.txt
> +Од техничка гледна точка, MP3-стандардот е целосно застарен но сеуште е многу успешен.
MP3 не е македонски збор.

2017-10-27 17:45 UTC, kjanko commented on macko996-2.txt
> +За да го калибрирате системот за снимање на движење, ве молиме да направите T-пози.
Т-пози?

2017-10-27 17:46 UTC, kjanko commented on macko996-2.txt
> +"Пред да си одиш, сакам да те гушнам", рече таа.
[а-шА-Ш1-9.!,?]

2017-10-27 17:46 UTC, kjanko commented on macko996-2.txt
> +"Ова е честа заблуда", рече Никола.
[а-шА-Ш1-9.!,?]

2017-10-27 17:46 UTC, kjanko commented on macko996-2.txt
> +Човечкиот мозок сè уште не е целосно разбран.
[а-шА-Ш1-9.!,?]

2017-10-27 17:47 UTC, kjanko requested changes
Ги искоментирав речениците што треба да се променат.

2017-10-27 19:00 UTC, macko996 commented on macko996-2.txt
> +"Пред да си одиш, сакам да те гушнам", рече таа.
Што не е во ред со реченицата?
[а-шА-Ш1-9.!,?] не објаснува ништо.

2017-10-29 11:29 UTC, dimitrovskif commented
@macko996 Под [а-шА-Ш1-9.!,?] се мисли израз што содржи само кирилични букви, цифри и интерпункциски знаци.

2017-10-30 08:38 UTC, merged

2017-10-30 08:55 UTC, dimitrovskif commented
@kjanko Има проблеми со празни линии:

https://github.com/kjanko/deep-speech-mk-sentences/blob/2aeb102eff54dc236c97ef597bd370e54605b079/macko996-2.txt#L324

https://github.com/kjanko/deep-speech-mk-sentences/blob/2aeb102eff54dc236c97ef597bd370e54605b079/macko996-2.txt#L320

Како и точка без ништо:

https://github.com/kjanko/deep-speech-mk-sentences/blob/2aeb102eff54dc236c97ef597bd370e54605b079/macko996-2.txt#L318

Не знам дали пречат?